# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "name": "Jefrey Epstine",
  "password": "shining",
  "type":"Pro"
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:4000/users/62823cb2c5a64ce9f1b50eb6/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/spider_net/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmVmcmV5IEVwc3RpbmUiLCJpZCI6IjY5ZGE2MTE0ODM5YjkwZTc3NGI4ZDZmMCIsImlhdCI6MTc3NjY4NDczOCwiZXhwIjoxNzc2ODU3NTM4fQ.xEULaohPTAYJFCQHl3xwAcS3u2rr4CSUf9kWlGfRv3g

###

## Добавить оффер в избранное
POST http://localhost:4000/offers/69de6dbca6ee245ff3c0364a HTTP/1.1
Content-Type: application/json

###
