# Предложения
## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###


## Добавить новое предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "name": "Уютный домик на остове",
  "description":"УютноУютноУютноУютноУютноУютно",
  "preview":"none",
  "price": 300,
  "isPremium":true,
  "isFavorite":false,
  "rating":5,
  "type":"Apartment",
  "authorId": "79cab3915b676cb07b52e135",
  "city":"Paris"
}

###

## Получить предложениt
GET http://localhost:4000/offers/69de6dbca6ee245ff3c0364a HTTP/1.1
Content-Type: application/json

###

## Изменить предложение
PATCH  http://localhost:4000/offers/69de6dbca6ee245ff3c0364a HTTP/1.1
Content-Type: application/json

{
  "name": "Не оочень уютный домик на остове"
}
###

## Удалить предложение
DELETE  http://localhost:4000/offers/69de6dbca6ee245ff3c0364a HTTP/1.1
Content-Type: application/json

###

## Добавить оффер в избранное
POST http://localhost:4000/offers/69de6dbca6ee245ff3c0364a/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmVmcmV5IEVwc3RpbmUiLCJpZCI6IjY5ZGE2MTE0ODM5YjkwZTc3NGI4ZDZmMCIsImlhdCI6MTc3OTI2MTQ3MCwiZXhwIjoxNzc5NDM0MjcwfQ.zM8AyoJZ2X36Cvsd9pAL-LAR3YoO-QCk13YU6vpwZcI
###

## Получить избранные офферы
GET http://localhost:4000/offers/me/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmVmcmV5IEVwc3RpbmUiLCJpZCI6IjY5ZGE2MTE0ODM5YjkwZTc3NGI4ZDZmMCIsImlhdCI6MTc3OTI2MTQ3MCwiZXhwIjoxNzc5NDM0MjcwfQ.zM8AyoJZ2X36Cvsd9pAL-LAR3YoO-QCk13YU6vpwZcI
###

## Удалить оффер из избранного
DELETE http://localhost:4000/offers/69de6dbca6ee245ff3c0364a/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmVmcmV5IEVwc3RpbmUiLCJpZCI6IjY5ZGE2MTE0ODM5YjkwZTc3NGI4ZDZmMCIsImlhdCI6MTc3OTI2MTQ3MCwiZXhwIjoxNzc5NDM0MjcwfQ.zM8AyoJZ2X36Cvsd9pAL-LAR3YoO-QCk13YU6vpwZcI
###
